### ISSUE TITLE
Add support for read-write capability

### ISSUE THREAD

**Issue by mmoayyed** [unicon-cas-addons/cas-addon-yaml-services-registry#1]
Registry is in read-only mode only, which cannot be used by the management interface.

**Comment by dima767** [comment]
This is deliberate. I am refusing to provide any read-write support for this. There are better suited backends for web UI - e.g. RDBMS

**Comment by mmoayyed** [comment]
This is requested by a client.

**Comment by mmoayyed** [comment]
Also, there is no reason this would have to be deliberate. For a single node simple setup, admined by one person, there's no good reason why a DB needs to be setup.

**Comment by dima767** [comment]
The whole purpose of this is to be used as is, via the file. I see no reason of adding RW complexity to this so it could be used just as a back end for web UI. If anything, client specific extension could be built on top of this. 

Sorry, don't want to sound radical here, just expressing my strong opinion about this :-)

**Comment by mmoayyed** [comment]
I understand, but don't see anything complex here. 

Compare:
1. A single file that is able to support the management interface by allowing RW functionality

with:
1. A database instance acquired
2. Schema created
3. Overhead of connection management and pooling
4. 1~3 needs to be done per tier (which in my case happens to be 4)

Also, without RW capability:
1. You'd force physical access into box; which is not always available
2. You'd risk typos and syntax weirdness and an additional linting process
3. You'd limit access to the file to a group who again, have only physical access
4. You'd introduce extra permissions and such on the file system
5. You'd force custom extensions on top of this addon, which should have been implemented as part of API contract.

This is a lot more complex than a few lines of code, specially if:
1. CAS is to be manned by only handful people
2. ...Who'd rather not physically edit the file
3. ...Who already have issues with syntax and linting
4. A single CAS node per tier

So what is this complexity you speak of? :)

**Comment by dima767** [comment]
Again, the purpose of this impl is to be simple file based access to be edited directly without complexities of transactional access.

If anything, the RW impl could be used outside of this lib. , on top of it.

What about native CAS JSON impl. ? Does it support RW, transactional access out of the box?

**Comment by dima767** [comment]
IMHO, embedded H2 database with file-based storage would be the best choice. Not much to set up as far as DBMS process, etc. just a single jar, bean config for the DB file location and standard CAS JPA svc registry config. Then you get the lightweight nature plus the transactional capability of H2 implementation.

**Comment by mmoayyed** [comment]
So, no file-based system storage can be transactional. We can safely cross that "feature" off :) The native JSON impl supports RW capabilities; it's not transactional as it can never be and also, it's not available until the next CAS release (4.1)

We should also consider that in this case atomic access to the file is irrelevant because it is simply not a concern. The file is only modified and touched by the active thread that runs the registry and is driven by a single user at one instant. There is no overhead of locking and such required. Because it simply does not apply. There is only a single admin attempting to modify the file, or a single app user attempting to add their own app into the list to whom the admin is not going to relinquish control of the CAS box. This is tightly controlled and we cane safely shrug any transactional responsibilities over to the client and say "hey, this is not designed for this kind of thing; even though you dont care for it now, it _may_ be an issue for you in the distant future" and let them worry about that.

I did bring up the JPA option as you pointed out. It is rejected because it serves no purpose...or no real purpose I should say for this particular deployment. 

Introducing transactional capabilities would in fact be extra complexity; that's something we can safely ignore. A H2 database would amount to be the same as a single YAML/JSON file if it's just going to ignore transactions anyway. Except that it's going to be more work to turn it on, and moving an H2 file system across tiers is not something a cron job would easily be able to do (which is another factor of unneeded complexity). 

I understand your viewpoint; that atomicity! can not be guaranteed. What I am also saying is, you can perfectly ignore issues and concerns and let the adopter worry about that, as we dont  and should not plan for that kind of thing. Majority of deployments that run a service registry with a JPA backend are manned not by 50 concurrent threads, but but only a handful of people incrementally and slow making mods to the system. They care about persistence, not transactional safety.
